#!/usr/bin/env python3
import os
import sys
import cs50
import helpers


from analyzer import Analyzer
from termcolor import colored


def main():
    
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    name=sys.argv[1]
    tweets=helpers.get_user_timeline(name)
    
    if tweets == None:
        print("Invalid user_name")
        sys.exit(1)
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(score, "green"),colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"),colored(tweet, "red"))
        else:
            print(colored(score, "yellow"),colored(tweet, "yellow"))

    
if __name__=="__main__":
    main()